/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.*;

import javax.swing.JOptionPane;
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        I = new javax.swing.JTextField();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        age = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        dis = new javax.swing.JTextField();
        blood = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        b = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 16, 550, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Donar Id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 16, 162, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 68, 162, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 114, 162, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Age");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 170, 162, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Blood Group");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 230, 162, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("District");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 414, 162, 38));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("mobile");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 286, 162, 38));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 342, 162, 38));

        n.setBackground(new java.awt.Color(204, 204, 204));
        n.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 72, 254, 38));

        I.setBackground(new java.awt.Color(204, 204, 204));
        I.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 20, 254, 38));

        m.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("Male");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        jPanel2.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 122, 98, -1));

        f.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Female");
        jPanel2.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 122, 109, -1));

        age.setBackground(new java.awt.Color(204, 204, 204));
        age.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 174, 256, 38));

        mob.setBackground(new java.awt.Color(204, 204, 204));
        mob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 286, 256, 38));

        dis.setBackground(new java.awt.Color(204, 204, 204));
        dis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 414, 256, 38));

        blood.setBackground(new java.awt.Color(204, 204, 204));
        blood.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 230, 256, 38));

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 342, 256, 38));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reg1.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 86, -1, 476));

        b.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b.setText("Submit");
        b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 588, 136, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 130, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reg.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
       
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/blood","root","ibrahim@2003");
            String sql="insert into donars(id,name,gender,age,blood,mobile,address,district) values(?,?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, I.getText());
            ps.setString(2, n.getText());
            if(m.isSelected()){
              ps.setString(3, "Male");
            }
            else if(f.isSelected()){
             ps.setString(3, "Female");
            }
            ps.setString(4, age.getText());
            ps.setString(5, blood.getText());
            ps.setString(6, mob.getText());
            ps.setString(7, add.getText());
            ps.setString(8, dis.getText());
            ps.execute();
            JOptionPane.showMessageDialog(rootPane, "Registration is done", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            details d=new details();
            d.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
           System.out.println(ex);
            JOptionPane.showMessageDialog(rootPane, "Registration is not done", "Failed",
                    JOptionPane.ERROR_MESSAGE);
        }
         

        
    }//GEN-LAST:event_bActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      details d=new details();
      d.setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField I;
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.JButton b;
    private javax.swing.JTextField blood;
    private javax.swing.JTextField dis;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField n;
    // End of variables declaration//GEN-END:variables
}
