/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;


public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        blood = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        dis = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 20, 550, 46));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Donar Id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 21, 162, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 73, 162, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 119, 162, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Age");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 169, 162, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Blood Group");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 225, 162, 38));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("mobile");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 281, 162, 38));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 337, 162, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("District");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 404, 162, 38));

        id.setBackground(new java.awt.Color(204, 204, 204));
        id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 21, 254, 38));

        n.setBackground(new java.awt.Color(204, 204, 204));
        n.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 71, 254, 38));

        g.setBackground(new java.awt.Color(204, 204, 204));
        g.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 121, 256, 38));

        blood.setBackground(new java.awt.Color(204, 204, 204));
        blood.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 227, 256, 38));

        mob.setBackground(new java.awt.Color(204, 204, 204));
        mob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 283, 256, 38));

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 339, 256, 38));

        dis.setBackground(new java.awt.Color(204, 204, 204));
        dis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 404, 256, 38));

        age.setBackground(new java.awt.Color(204, 204, 204));
        age.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 171, 256, 38));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 93, 550, 475));

        button.setBackground(new java.awt.Color(102, 102, 102));
        button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Update");
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 146, -1));

        button1.setBackground(new java.awt.Color(102, 102, 102));
        button1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Back");
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 146, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update1.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/blood","root","ibrahim@2003");
            String sql="Update donars set name=?,gender=?,age=?,blood=?,mobile=?,address=?,district=? where id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, n.getText());
            ps.setString(2, g.getText());
            ps.setString(3, age.getText());
            ps.setString(4, blood.getText());
            ps.setString(5, mob.getText());
            ps.setString(6, add.getText());
            ps.setString(7, dis.getText());
            ps.setString(8, id.getText()); 
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Changes are Updated", "Success", 
                        JOptionPane.INFORMATION_MESSAGE);
            details d=new details();
            d.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            System.out.println(ex);
            
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/blood","root","ibrahim@2003");
            String sql="Select*from donars where id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, id.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                n.setText(rs.getString("name"));
                g.setText(rs.getString("gender"));
                age.setText(rs.getString("age"));
                blood.setText(rs.getString("blood"));
                mob.setText(rs.getString("mobile"));
                add.setText(rs.getString("address"));
                dis.setText(rs.getString("district"));
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Data not found","Failed",
                        JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
           System.out.println(ex);
        }   
       }
    }//GEN-LAST:event_idKeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       details d=new details();
       d.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.JTextField blood;
    private javax.swing.JButton button;
    private javax.swing.JButton button1;
    private javax.swing.JTextField dis;
    private javax.swing.JTextField g;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField n;
    // End of variables declaration//GEN-END:variables
}
